import Head from 'next/head';
import type { NextPage } from 'next';

import OwnedNftGallery from '../components/OwnedNftGallery';

const Account: NextPage = () => {
  return (
    <>
      <Head>
        <title>JpegPon - account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" sizes="32x32" href="/favicon-32.png" />
        <link rel="icon" sizes="16x16" href="/favicon-16.png" />
      </Head>
      <OwnedNftGallery />
    </>
  );
};

export default Account;
